-- Create the database
-- CREATE DATABASE IHME_GROUP_1
-- GO


-- Use the database
USE IHME_GROUP_1
GO


DROP TABLE tblREGION
CREATE TABLE tblREGION
(RegionID INT IDENTITY(1,1) PRIMARY KEY,
RegionName VARCHAR(50) NOT NULL)
GO

DROP TABLE tblCOUNTRY
CREATE TABLE tblCOUNTRY
(CountryID INT IDENTITY(1,1) PRIMARY KEY,
RegionID INT FOREIGN KEY REFERENCES tblREGION (RegionID) NOT NULL,
CountryName VARCHAR(50) NOT NULL)
GO

CREATE TABLE tblDSTYPE
(DstypeID INT IDENTITY(1,1) PRIMARY KEY,
DstypeName VARCHAR(50) NOT NULL)
GO

CREATE TABLE tblSEX
(SexID INT IDENTITY(1,1) PRIMARY KEY,
SexName VARCHAR(8) NOT NULL)
GO

CREATE TABLE tblAGE
(AgeID INT IDENTITY(1,1) PRIMARY KEY,
AgeGroupName VARCHAR(8) NOT NULL)
GO

DROP TABLE tblCASE
CREATE TABLE tblCASE
(CaseID INT IDENTITY(1,1) PRIMARY KEY,
CountryID INT FOREIGN KEY REFERENCES tblCOUNTRY (CountryID) NOT NULL,
DstypeID INT FOREIGN KEY REFERENCES tblDSTYPE (DstypeID) NOT NULL,
SexID INT FOREIGN KEY REFERENCES tblSEX (SexID) NOT NULL,
AgeID INT FOREIGN KEY REFERENCES tblAGE (AgeID) NOT NULL,
CaseYear CHAR(4) NOT NULL,
CaseValue NUMERIC(15,8) NOT NULL)
GO

SELECT*FROM IHME_raw_data
GO